### ISSUE TITLE
Getting Error: No source folder defined. Check configuration.

### ISSUE THREAD

**Issue by venkiteelay** [ModusCreateOrg/nightwatch-cucumber-demo#2]
Hi, 
I am trying to execute the tests and I am getting below error. Could you please help me in resolving this issue.
There was an error while starting the test runner:
`Error: No source folder defined. Check configuration.
    at Function.Runner.readPaths (C:\Users\yventikeela\IdeaProjects\nightwatch-cucumber-demo\node_modules\nightwatch\lib\runner\run.js:192:11)
    at Runner.runner [as run] (C:\Users\yventikeela\IdeaProjects\nightwatch-cucumber-demo\node_modules\nightwatch\lib\runner\run.js:235:10)
    at CliRunner.runner (C:\Users\yventikeela\IdeaProjects\nightwatch-cucumber-demo\node_modules\nightwatch\lib\runner\cli\clirunner.js:443:23)
    at C:\Users\yventikeela\IdeaProjects\nightwatch-cucumber-demo\node_modules\nightwatch\lib\runner\cli\clirunner.js:395:12
    at SeleniumServer.onStarted (C:\Users\yventikeela\IdeaProjects\nightwatch-cucumber-demo\node_modules\nightwatch\lib\runner\cli\clirunner.js:354:9)
    at SeleniumServer.checkProcessStarted (C:\Users\yventikeela\IdeaProjects\nightwatch-cucumber-demo\node_modules\nightwatch\lib\runner\selenium.js:148:10)
    at SeleniumServer.onStderrData (C:\Users\yventikeela\IdeaProjects\nightwatch-cucumber-demo\node_modules\nightwatch\lib\runner\selenium.js:128:8)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20)
`

**Comment by jogjitu** [comment]
@venkiteelay can try with latest version. I found another issue reference [here](https://github.com/mucsi96/nightwatch-cucumber/commit/19db01e33c5deabd6fc872f5dcb71b7cb7bbacfd)
